language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

env: REPORT_EXIT_STATUS=1

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential python unzip
    - mkdir libcryptopp
    - cd libcryptopp
    - wget http://www.cryptopp.com/cryptopp562.zip
    - unzip cryptopp562.zip
    - sed -i -e 's/^CXXFLAGS/#CXXFLAGS/' GNUmakefile
    - export CXXFLAGS="${CXXFLAGS} -DNDEBUG -fPIC"
    - make -f GNUmakefile
    - make libcryptopp.so
    - sudo make install
    - cd ..

before_script:
    - ulimit -c unlimited || true
    - phpize && ./configure && make && sudo make install

script:
    - MYPHP=$(phpenv which php)
    - ZEND_DONT_UNLOAD_MODULES=1 REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$MYPHP $MYPHP run-tests.php -q --show-diff -d extension=cryptopp.so

after_failure:
    - sudo apt-get install -qq gdb
    - MYPHP=$(phpenv which php)
    - for i in $(find . -name 'core*' -print); do gdb -c "$i" "$MYPHP" -ex "thread apply all bt" -ex "set pagination 0" -ex "backtrace full" -ex "info registers" -ex "x/16i \$pc" -batch; done;

notifications:
    email:
        - stephen.berquet@gmail.com
